# Generated by Django 3.2.5 on 2021-07-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('address', models.TextField(blank=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.university')),
            ],
        ),
    ]
