# Generated by Django 3.2.5 on 2021-07-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=255)),
                ('uni_address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
